site_name: CBDT的资料屋
site_url: https://note.weitao-jiang.cn
docs_dir: docs
repo_url: https://github.com/CBDT-JWT/EEnotes
repo_name: CBDT-JWT/EEnotes
use_directory_urls: true
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
copyright: |
  Copyright &copy; 2024 - 2026 Weitao JIANG. <br>
  <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener noreferrer">京ICP备2025155858号-1</a> | 
  <a href="https://beian.mps.gov.cn/#/query/webSearch?code=11010802047067" rel="noreferrer" target="_blank">京公网安备11010802047067号</a> | 
  <a href="https://icp.gov.moe/?keyword=20268192" target="_blank">萌ICP备20268192号</a>
markdown_extensions:
  - def_list
  - neoteroi.timeline
  - footnotes
  - pymdownx.arithmatex:
       generic: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  
extra_css:
- css/neoteroi-mkdocs.css
- stylesheets/blogviewer.css
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css

nav:
  - 主页: https://www.weitao-jiang.cn
  - 序言: index.md
  - 数理基础:
    - 线性代数(1): linear-algebra-1.md
    - 线性代数(2): linear-algebra-2.md
    - 大学物理（热学）: thermo-physics.md
  - 物理-电磁组:  
    - 电磁场与电磁波: electromagnetic-fields-and-waves.md
    - 量子与统计: quantum-and-statistics.md
    - 固体物理: solid-state-physics.md
  - 电路组:
    - 电子电路与系统基础: fundamentals-of-electronic-circuits.md
    - 模拟电路原理: analog-circuits.md
    - 数字逻辑与处理器基础: digital-logic-and-processors.md
    - 微波与光波技术基础: microwave-engineering-basics.md
  - 信号组:
    - 信号与系统: signals-and-systems.md
    - 数字信号处理: digital-signal-processing.md
    - 通信与网络: communication-and-networks.md
    - 随机过程: stochastic-processes.md
  - 计算机组:
    - 程设基础: c-and-c++-programming.md
    - 数据结构与算法: dsa.md
    - 媒体与认知: media-and-cognition.md
  - 科研与工具:
    - Matlab高级编程与工程应用: matlab.md
    - 高等模拟电路原理: advanced-analog-circuits.md
    - 模拟数字数据转换器: AD-and-DA-convertors.md
    - 电源管理芯片: Power-IC-Basics.md
    - OrCAD使用笔记: orcad-and-allegro.md
    - Latex基础教程: latex-tutorial.md
    
  - 开往: https://www.travellings.cn/go.html
theme:
  name: material
  logo: https://www.weitao-jiang.cn/images/avatar.jpg
  favicon: https://www.weitao-jiang.cn/images/favicon.ico
  custom_dir: overrides
  palette: 
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: zh
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - attr_list
    - md_in_html
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      
extra_javascript:
- javascripts/navigation.js
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
- https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
- https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js
- https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
- https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.6/underscore-min.js
- https://cdn.jsdelivr.net/npm/@mermaid-js/mermaid-mindmap@9.3.0/dist/diagram-definition.0faef4c2.min.js
- https://cdn.jsdelivr.net/npm/markdown-it-plantuml@1.4.1/index.min.js
- https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml-full.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-svg-full.js
#- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
#- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

extra:
  social:
    - icon: octicons/mail-16
      link: mailto:cbdt@weitao-jiang.cn
    - icon: octicons/link-16
      link: https://www.weitao-jiang.cn
